// Code generated by "stringer -type=Layout"; DO NOT EDIT

package geom

import "fmt"

const _Layout_name = "EmptyXYXYZXYMXYZM"

var _Layout_index = [...]uint8{0, 5, 7, 10, 13, 17}

func (i Layout) String() string {
	if i < 0 || i >= Layout(len(_Layout_index)-1) {
		return fmt.Sprintf("Layout(%d)", i)
	}
	return _Layout_name[_Layout_index[i]:_Layout_index[i+1]]
}
