name: main
on:
  pull_request:
  push:
env:
  GOFUMPT_VERSION: 0.10.0
  GOLANGCI_LINT_VERSION: 2.12.2
jobs:
  linux:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd   # v6.0.2
    - uses: actions/setup-go@4a3601121dd01d1626a1e23e37211e3254c1c06c   # v6.4.0
      with:
        cache: true
        go-version-file: go.mod
    - name: build
      run: go build ./...
    - name: test
      run: go test -race -tags=docker ./...
    - name: Check formatting
      run: |
        make format
        git diff --exit-code
    - name: Check generate
      run: |
        make generate
        git diff --exit-code
  darwin:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd   # v6.0.2
    - uses: actions/setup-go@4a3601121dd01d1626a1e23e37211e3254c1c06c   # v6.4.0
      with:
        cache: true
        go-version-file: go.mod
    - name: build
      run: go build ./...
    - name: test
      run: go test -race  ./...
  windows:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd   # v6.0.2
    - uses: actions/setup-go@4a3601121dd01d1626a1e23e37211e3254c1c06c   # v6.4.0
      with:
        cache: true
        go-version-file: go.mod
    - name: build
      run: go build ./...
    - name: test
      run: go test -race ./...
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd   # v6.0.2
      - uses: actions/setup-go@4a3601121dd01d1626a1e23e37211e3254c1c06c   # v6.4.0
        with:
          cache: true
          go-version-file: go.mod
      - uses: golangci/golangci-lint-action@1e7e51e771db61008b38414a730f564565cf7c20   # v9.2.0
        with:
          version: v${{ env.GOLANGCI_LINT_VERSION }}
      - name: format
        run: make format